### ISSUE TITLE
Levantamento de Funcionalidades

### ISSUE THREAD

**Issue by josetvictor** [josetvictor/stock-management#2]
- Camadas do projeto
  - [x] Persistencia
  - [x] Negocio
  - [x] Modelo
  - [x] Visão
- Autenticação
  - [x] Login
  - [x] Hierarquia de usuários

**Comment by josetvictor** [comment]
- Persistência 
   - [ ] Função para abrir JSON
   - [ ] Função para salvar objetos no JSON

**Comment by josetvictor** [comment]
- Visão
   - [ ] Relação de visão com negocio

**Comment by lucashec** [comment]
- Visão:
Faltando apenas a parte para retornar a nota adicionada no grid e vincular cada itemNF com a sua nota, no mais, creio que esteja tudo funcionando, digo, as opções de emitir e filtrar produtos.
**OBS: também se aplica para  a tela de recebimento.

**Comment by lucashec** [comment]
Funcionalidades para implementar 10/12:

- [ ] ReadOnly com bind na Main/XGH
- [ ] Criar arquivo JSON camada de Negócio
- [ ] Instanciar buttons para UserControl
